### ISSUE TITLE
I hope all the methods in the pylons-sdk should be implemented in the pylons-dart-sdk. 

### ISSUE THREAD

**Issue by Booyoun-Kim** [Pylons-tech/pylons_dart_sdk#38]
Pylons-sdk is private, so all the methods required for pylons-dart-sdk should be implemented, but they are not. Please add all methods, including get-item, in pylons-dart-sdk. Perhaps Hackatom participants may feel it difficult to develop games because of this barrier.

**Comment by kjawadDeveloper2** [comment]
We are looking into it and provide a solution soon.

**Comment by kjawadDeveloper2** [comment]
Added support for get execution list by id.

**Comment by Booyoun-Kim** [comment]
@kjawadDeveloper2 Thank you 😊

**Comment by kjawadDeveloper2** [comment]
Added support for getItemById.
